apiVersion: v1
kind: Pod
metadata:
  name: test-hook
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  restartPolicy: Never
  serviceAccountName: hook-delete
  automountServiceAccountToken: true
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot:  true
  containers:
    - name: post-delete-job
      image: "bitnami/kubectl:1.26.12"
      command: ["kubectl","annotate","ns","{{ .Release.Namespace }}", "--overwrite", "damien-to-delete=True"]
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot:  true

