kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hook
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
subjects:
- kind: ServiceAccount
  name: hook-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  hook
